version: "3.7"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile.dev
    ports:
        - "3030:3030"
        - "6006:6006"
    volumes:
        - .:/app
        - /app/node_modules
    environment:
        NODE_ENV: development
    tty:
        true