# base image
FROM node:18-alpine3.14

  # set working directory
WORKDIR /app

  # copy package.json and package-lock.json
COPY ../../package*.json ./

#  #yarn.lockをコピーする場合
COPY ../../yarn.lock ./
#
# install dependencies
#RUN yarn
#
RUN yarn install

# copy source files
COPY ../../ .
  # expose port 3030
EXPOSE 3030

  # start the app in development mode
CMD ["yarn", "dev", "--port", "3030"]